#!/usr/bin/python3

import os
import sys
import functools
import typing
import datetime
from sortedcontainers import SortedSet


@functools.total_ordering
class Record:
  def __init__(self, day: int, month: int, year: int, hour: int, minute: int, task: str):
    self.dated_task = (year, month, day, hour, minute, task)


  def __eq__(self, other: typing.Self) -> bool:
    return self.dated_task == other.dated_task
  
  
  def __lt__(self, other: typing.Self) -> bool:
    return self.dated_task < other.dated_task
  

  def __str__(self):
    year = str(self.dated_task[0]).zfill(4)
    month = str(self.dated_task[1]).zfill(2)
    day = str(self.dated_task[2]).zfill(2)
    hour = str(self.dated_task[3]).zfill(2)
    minute = str(self.dated_task[4]).zfill(2)
    return f"{day}.{month}.{year} {hour}:{minute} {self.dated_task[5]}"
  

  def __hash__(self):
    return hash(self.dated_task)


def Parse(line: str) -> Record:
  """example:\n
  19.10.2025 11:25 do deadliner app"""
  return Record(
    int(line[0:2]),
    int(line[3:5]),
    int(line[6:10]),
    int(line[11:13]),
    int(line[14:16]),
    line[17:]
  )


def Init(data_path: str) -> SortedSet[Record]:
  result = SortedSet()
  with open(data_path, 'r') as data:
    for line in data.readlines():
      result.add(Parse(line.strip()))
  return result


def Save(sorted_set: SortedSet[Record], data_path: str) -> None:
  with open(data_path, 'w') as data:
    for record in sorted_set:
      data.write(str(record) + '\n')


def Validate(date: str, time: str) -> bool:
  # length check
  check = len(date) in (5, 10) and len(time) in (1, 5)
  if not check:
    return False
  
  # format check
  check = date[0:2].isdigit() and date[3:5].isdigit()
  if len(date) == 10:
    check = check and date[6:10].isdigit()

  if len(time) == 1:
    check = check and time[0] == '_'
  else:
    check = check and time[0:2].isdigit() and time[3:5].isdigit()

  if not check:
    return False
  
  # semantics_check
  check = (1 <= int(date[0:2]) <= 31) and (1 <= int(date[3:5]) <= 12)
  if len(time) == 5:
    check = check and 0 <= int(time[0:2]) <= 23 and 0 <= int(time[3:5]) <= 59

  return check


def Date(date: str) -> str:
  if len(date) == 10:
    return date
  return f"{date}.{datetime.datetime.now().year}"


def Time(time: str) -> str:
  if len(time) == 5:
    return time
  return '23:59'


def Top(sorted_set: SortedSet[Record]) -> None:
  if len(sorted_set) > 0:
    print(sorted_set[0])


def All(sorted_set: SortedSet[Record]) -> None:
  for record in sorted_set:
    print(record)


def main():
  data_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')
  sorted_set = Init(data_path)

  if len(sys.argv) > 2:
    print("Invalid argument count.")
    sys.exit(-1)

  if len(sys.argv) == 2:
    if sys.argv[1] not in ('--top', '--all'):
      print("Unknown flag.")
      sys.exit(-1)
    if sys.argv[1] == '--top':
      Top(sorted_set)
    else:
      All(sorted_set)
      
    return

  while True:
    command = input().split(' ', maxsplit=3)
    if len(command) == 1 and command[0] in ('pop', 'top', 'all', 'exit'):
      if command[0] == 'top':
        Top(sorted_set)
      elif command[0] == 'all':
        All(sorted_set)
      elif command[0] == 'pop':
        if len(sorted_set) > 0:
          del sorted_set[0]
      else: # command[0] == 'exit':
        Save(sorted_set, data_path)
        break
    elif len(command) == 4 and command[0] in ('add', 'remove', 'rm') and Validate(command[1], command[2]):
      record = Parse(' '.join((Date(command[1]), Time(command[2]), command[3])))
      if command[0] == 'add':
        sorted_set.add(record)
      else: # command[0] == 'remove' or 'rm'
        if record in sorted_set:
          sorted_set.remove(record)
    else:
      print('Unknown command.')


if __name__ == "__main__":
  main()
